routes/web.php
<?php

Auth::routes();
Route::group(['middleware' => ['auth']], function () {
    Route::get('/simple', 'SimpleController@simpleGeneticAlgorithms');

    Route::get('/', 'MainController@home')->name('home');
    Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout')->name('logout');
    Route::get('/ubah-password', 'MainController@changePassword')->name('ubah.password');
    Route::put('/ubah-password', 'MainController@updatePassword')->name('update.password');

    Route::resource('/waktu', 'TimeController');
    Route::resource('/kelas', 'GradeController');
    Route::resource('/pelajaran', 'SubjectController');
    Route::resource('/guru', 'TeacherController');

    //Tugas
    Route::get('/tugas', 'TaskController@index')->name('tugas.index');
    Route::get('/tugas/create/{id?}', 'TaskController@create')->name('tugas.create');
    Route::post('/tugas', 'TaskController@store')->name('tugas.store');
    Route::get('/tugas/{teacher_id}/{subject_id}', 'TaskController@edit')->name('tugas.edit');
    Route::put('/tugas/{teacher_id}/{subject_id}', 'TaskController@update')->name('tugas.update');
    Route::delete('/tugas/{teacher_id}/{subject_id}', 'TaskController@destroy')->name('tugas.destroy');

    Route::get('/jadwal/preview', 'ScheduleController@preview')->name('jadwal.preview');
    Route::get('/jadwal/cetak', 'ScheduleController@cetak')->name('jadwal.cetak');
    Route::resource('/jadwal', 'ScheduleController');

    Route::get('/generate', 'GenerateController@index')->name('generate.index');
    Route::get('/generate-jadwal', 'GenerateController@generate')->name('generate.jadwal');
    Route::post('/generate-jadwal', 'GenerateController@store')->name('generate.jadwal.store');

    Route::get('/ajax/tugas-guru/{id}', 'AjaxController@TaskTeacher');
    Route::get('/ajax/hari/{id}', 'AjaxController@day');
    Route::get('/ajax/kelas/{id}', 'AjaxController@grade');
    Route::get('/ajax/mata-pelajaran/{id}', 'AjaxController@subjectByClass');
    Route::get('/ajax/guru/{classLevelId}/{subjectId}/', 'AjaxController@teacher');

    Route::get('/home', 'MainController@home')->name('home');
});

resources/views/app/pelajaran/create.blade.php
@extends('layouts.app')

@section('content')
<div class="card">
    <div class="card-body">
        <h5 class="card-title">Tambah Pelajaran</h5>
        @include('includes.pesan')
        <form action="{{ route('pelajaran.store') }}" method="post">
            @csrf
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="">Nama Mata Pelajaran</label>
                        <input type="text" name="nama" class="form-control" value="{{ old('nama') }}">
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label for="">Total Jam Pelajaran</label>
                        <input type="number" name="jam" class="form-control" value="{{ old('jam_pelajaran') }}" min="1" max="4">
                        <div class="form-text text-muted">Direkomendasikan input 1 - 4 jam</div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label id="labelKelas" for="">Kelas</label>
                        @component('components.forms.checkKelas', [
                        'subject' => session('store') ?? null,
                        'classes' => $classes
                        ])
                        @endcomponent
                    </div>
                </div>
            </div>

            <button type="submit" class="btn btn-success mr-2">Simpan</button>
            <a href="{{ session('url_pelajaran') }}">
                <button type="button" class="btn btn-secondary mr-2">Kembali</button>
            </a>
        </form>
    </div>
</div>
@endsection

@section('scripts')
<script>
    $("#semuaKelas").click(function () {
        $('input[name="classes[]"]').prop('checked', this.checked);
    });
</script>
@endsection

resources/views/app/pelajaran/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="card">
    <div class="card-body">
        <h5 class="card-title">Edit Mata Pelajaran</h5>
        @include('includes.pesan')
        <form action="{{ route('pelajaran.update', $subject->id) }}" method="post">
            @csrf
            @method('PUT')
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="">Nama Mata Pelajaran</label>
                        <input type="text" name="nama" class="form-control" value="{{ old('nama', $subject->nama) }}">
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label for="">Total Jam Pelajaran</label>
                        <label for="">Jam Pelajaran / Pertemuan</label>
                        <input type="number" name="jam" class="form-control" value="{{ old('jam_pelajaran', $subject->jam) }}" min="1" max="4">
                        <div class="form-text text-muted">Direkomendasikan input 1 - 4 jam</div>
                    </div>
                </div>
                <div class="col-md-5">
                    <div class="form-group">
                        <label for="">Kelas</label>
                        @component('components.forms.checkKelas', [
                            'subject' => $subject,
                            'classes' => $classes
                        ])
                        @endcomponent
                    </div>
                </div>
            </div>

            <button type="submit" class="btn btn-success mr-2">Simpan</button>
            <a href="{{ session('url_pelajaran') }}">
                <button type="button" class="btn btn-secondary mr-2">Kembali</button>
            </a>
        </form>
    </div>
</div>
@endsection

resources/views/app/pelajaran/index.blade.php
@extends('layouts.app')

@section('content')
<div class="card">
    <div class="card-body">
        <h5 class="card-title">Mata Pelajaran</h5>
        @include('includes.pesan')
        <form class="form-inline mb-3" action="{{ route('pelajaran.index') }}">
            <input type="text" name="nama" class="form-control mb-2 mr-2" placeholder="Mata Pelajaran" value="{{ request()->nama }}">
            @component('components.forms.selectKelas', [
                    'class' => 'mb-2 mr-2',
                    'null' => true,
                    'value' => request()->kelas
                ])
            @endcomponent
            @component('components.forms.selectJurusan', [
                    'class' => 'mb-2 mr-2',
                    'null' => true,
                    'value' => request()->major_id
                ])
            @endcomponent
            <button type="submit" class="btn btn-primary mb-2 mr-1" type="button"><i class="fas fa-search"></i></button>
            <a href="{{ route('pelajaran.create') }}" class="btn btn-success mb-2 mr-1"><i class="fas fa-plus"></i></a>
            <a href="{{ route('pelajaran.index') }}" class="btn btn-info mb-2 mr-1"><i class="fas fa-sync-alt"></i></a>
            <a href="{{ route('home') }}" class="btn btn-secondary mb-2 mr-1"><i class="fas fa-arrow-left"></i></a>
        </form>

        <table class="table table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Mata Pelajaran</th>
                    <th class="text-center">Total Jam</th>
                    @foreach ($classLevels as $class)
                        <th class="text-center">{{ $class->nama }}</th>
                    @endforeach
                    <th class="text-right pr-4">aksi</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($subjects as $subject)
                <tr @if($subject->id == session()->get('updated_id')) class="table-success" @endif>
                    <td>{{ ($subjects->currentpage() - 1) * $subjects->perPage() + $loop->iteration }}.</td>
                    <td>{{ $subject->nama }}</td>
                    <td class="text-center">{{ $subject->total_jam_pelajaran }}</td>
                    @foreach ($classLevels as $key => $class)
                        <td class="text-center">
                            @if (in_array($class->id, $subject->classes->pluck('id')->toArray()))
                                <i class="fas fa-check text-success "></i>
                            @endif
                        </td>
                    @endforeach
                    <td class="text-right">
                        <a href="{{ route('pelajaran.edit', $subject->id) }}">
                            <i class="fas fa-edit text-info mr-2"></i>
                        </a>
                        <form method="POST" class="d-inline-block" action="{{ route('pelajaran.destroy', $subject->id) }}">
                            @csrf
                            @method('DELETE')
                            <a href="#" class="btn-delete">
                                <i class="fas fa-times text-danger mr-2"></i>
                            </a>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
            <tfoot>
                <tr>
                    <th class="text-center" colspan="2">TOTAL</th>
                    <th class="text-center">{{ $total->total_jam_pelajaran}}</th>
                    <th class="text-center">{{ $total->total_pertemuan }}</th>
                    <th colspan="{{ 2 + $classLevels->count() }}"></th>
                </tr>
            </tfoot>
        </table>

        <div class="d-flex justify-content-center">
            {{ $subjects->appends($_GET)->links() }}
        </div>
    </div>
</div>
@endsection