routes/web.php
<?php

Auth::routes();
Route::group(['middleware' => ['auth']], function () {
    Route::get('/simple', 'SimpleController@simpleGeneticAlgorithms');

    Route::get('/', 'MainController@home')->name('home');
    Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout')->name('logout');
    Route::get('/ubah-password', 'MainController@changePassword')->name('ubah.password');
    Route::put('/ubah-password', 'MainController@updatePassword')->name('update.password');

    Route::resource('/waktu', 'TimeController');
    Route::resource('/kelas', 'GradeController');
    Route::resource('/pelajaran', 'SubjectController');
    Route::resource('/guru', 'TeacherController');

    //Tugas
    Route::get('/tugas', 'TaskController@index')->name('tugas.index');
    Route::get('/tugas/create/{id?}', 'TaskController@create')->name('tugas.create');
    Route::post('/tugas', 'TaskController@store')->name('tugas.store');
    Route::get('/tugas/{teacher_id}/{subject_id}', 'TaskController@edit')->name('tugas.edit');
    Route::put('/tugas/{teacher_id}/{subject_id}', 'TaskController@update')->name('tugas.update');
    Route::delete('/tugas/{teacher_id}/{subject_id}', 'TaskController@destroy')->name('tugas.destroy');

    Route::get('/jadwal/preview', 'ScheduleController@preview')->name('jadwal.preview');
    Route::get('/jadwal/cetak', 'ScheduleController@cetak')->name('jadwal.cetak');
    Route::resource('/jadwal', 'ScheduleController');

    Route::get('/generate', 'GenerateController@index')->name('generate.index');
    Route::get('/generate-jadwal', 'GenerateController@generate')->name('generate.jadwal');
    Route::post('/generate-jadwal', 'GenerateController@store')->name('generate.jadwal.store');

    Route::get('/ajax/tugas-guru/{id}', 'AjaxController@TaskTeacher');
    Route::get('/ajax/hari/{id}', 'AjaxController@day');
    Route::get('/ajax/kelas/{id}', 'AjaxController@grade');
    Route::get('/ajax/mata-pelajaran/{id}', 'AjaxController@subjectByClass');
    Route::get('/ajax/guru/{classLevelId}/{subjectId}/', 'AjaxController@teacher');

    Route::get('/home', 'MainController@home')->name('home');
});

app/Models/Grade.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Grade extends Model
{
    protected $fillable = ['nama', 'kelas', 'major_id'];

    public function class()
    {
        return $this->belongsTo('App\Models\ClassLevel', 'class_level_id');
    }

    public function getKelasAttribute()
    {
        return $this->class->kelas;
    }

    public function getJurusanAttribute()
    {
        return $this->class->major->nama ;
    }

    public static function fetch($request, $paginate = 10)
    {
        return self::where(function ($query) use ($request) {
                if ($request->nama) $query->where('nama', 'like', "%$request->nama%");
            })
            ->whereHas('class', function($query) use ($request) {
                if ($request->kelas) $query->where('kelas', "$request->kelas");
                if ($request->major_id) $query->where('major_id', "$request->major_id");
            })
            ->with('class', 'class.major')
            ->orderBy('class_level_id')
            ->orderBy('nama')
            ->paginate($paginate);
    }

    public static function joinClassLevels()
    {
        return self::join('class_levels', 'class_levels.id', '=', 'grades.class_level_id')
            ->select('grades.nama', 'grades.class_level_id', 'grades.id', 'class_levels.nama as level')
            ->orderBy('grades.class_level_id')
            ->orderBy('grades.nama')
            ->get();
    }

    public static function byClassLevelId($id)
    {
        $classLevels = ClassLevel::all();
        $class = [];
        foreach ($classLevels as $key => $level) {
            $class[] = self::where('class_level_id', $level->id)->get();
        }
        return $class;
    }
}

resources/views/app/kelas/create.blade.php
@extends('layouts.app')

@section('content')
<div class="card container">
    <div class="card-body">
        <h5 class="card-title">Tambah Kelas</h5>
        @include('includes.pesan')
        <form action="{{ route('kelas.store') }}" method="post">
            @csrf
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="">Kelas</label>
                        @component('components.forms.selectKelas', [
                                'value' => old('kelas', session('store.kelas'))
                            ])
                        @endcomponent
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="">Jurusan</label>
                        @component('components.forms.selectJurusan', [
                                'value' => old('major_id', session('store.major_id'))
                            ])
                        @endcomponent
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="">Nama Kelas</label>
                        <input type="text" name="nama" class="form-control" value="{{ old('nama') }}">
                    </div>
                </div>
            </div>

            <button type="submit" class="btn btn-success mr-2">Simpan</button>
            <a href="{{ session('url_kelas') }}">
                <button type="button" class="btn btn-secondary mr-2">Kembali</button>
            </a>
        </form>
    </div>
</div>
@endsection

resources/views/app/kelas/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="card container">
    <div class="card-body">
        <h5 class="card-title">Edit Waktu</h5>
        @include('includes.pesan')
        <form action="{{ route('kelas.update', $grade->id) }}" method="post">
            @csrf
            @method('PUT')
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="">Kelas</label>
                        @component('components.forms.selectKelas', [
                                'value' => old('kelas', $grade->kelas)
                            ])
                        @endcomponent
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="">Jurusan</label>
                        @component('components.forms.selectJurusan', [
                                'value' => old('major_id', $grade->class->major_id)
                            ])
                        @endcomponent
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="">Nama Kelas</label>
                        <input type="text" name="nama" class="form-control" value="{{ old('nama', $grade->nama) }}">
                    </div>
                </div>
            </div>

            <button type="submit" class="btn btn-success mr-2">Simpan</button>
            <a href="{{ session('url_kelas') }}">
                <button type="button" class="btn btn-secondary mr-2">Kembali</button>
            </a>
        </form>
    </div>
</div>
@endsection

resources/views/app/kelas/index.blade.php
@extends('layouts.app')

@section('content')
<div class="card container">
    <div class="card-body">
        <h5 class="card-title">Kelas</h5>
        @include('includes.pesan')
        <form class="form-inline mb-3" action="{{ route('kelas.index') }}">
            <input type="text" name="nama" class="form-control mb-2 mr-2" placeholder="Kelas" value="{{ request()->nama }}">
            @component('components.forms.selectKelas', [
                    'class' => 'mb-2 mr-2',
                    'null' => true,
                    'value' => request()->kelas
                ])
            @endcomponent
            @component('components.forms.selectJurusan', [
                    'class' => 'mb-2 mr-2',
                    'null' => true,
                    'value' => request()->major_id
                ])
            @endcomponent
            <button type="submit" class="btn btn-primary mb-2 mr-1" type="button"><i class="fas fa-search"></i></button>
            <a href="{{ route('kelas.create') }}" class="btn btn-success mb-2 mr-1"><i class="fas fa-plus"></i></a>
            <a href="{{ route('kelas.index') }}" class="btn btn-info mb-2 mr-1"><i class="fas fa-sync-alt"></i></a>
            <a href="{{ route('home') }}" class="btn btn-secondary mb-2 mr-1"><i class="fas fa-arrow-left"></i></a>
        </form>

        <table class="table table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Kelas / Jurusan</th>
                    <th>Kelas</th>
                    <th>Jurusan</th>
                    <th class="text-right pr-4">aksi</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($grades as $grade)
                <tr @if($grade->id == session()->get('updated_id')) class="table-success" @endif>
                    <td>{{ ($grades->currentpage() - 1) * $grades->perPage() + $loop->iteration }}.</td>
                    <td>{{ $grade->nama }}</td>
                    <td>{{ $grade->kelas }}</td>
                    <td>{{ $grade->jurusan }}</td>
                    <td class="text-right">
                        <a href="{{ route('kelas.edit', $grade->id) }}">
                            <i class="fas fa-edit text-info mr-2"></i>
                        </a>
                        <form method="POST" class="d-inline-block" action="{{ route('kelas.destroy', $grade->id) }}">
                            @csrf
                            @method('DELETE')
                            <a href="#" class="btn-delete">
                                <i class="fas fa-times text-danger mr-2"></i>
                            </a>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>

        <div class="d-flex justify-content-center">
            {{ $grades->appends($_GET)->links() }}
        </div>
    </div>
</div>
@endsection