routes/web.php
<?php

Auth::routes();
Route::group(['middleware' => ['auth']], function () {
    Route::get('/simple', 'SimpleController@simpleGeneticAlgorithms');

    Route::get('/', 'MainController@home')->name('home');
    Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout')->name('logout');
    Route::get('/ubah-password', 'MainController@changePassword')->name('ubah.password');
    Route::put('/ubah-password', 'MainController@updatePassword')->name('update.password');

    Route::resource('/waktu', 'TimeController');
    Route::resource('/kelas', 'GradeController');
    Route::resource('/pelajaran', 'SubjectController');
    Route::resource('/guru', 'TeacherController');

    //Tugas
    Route::get('/tugas', 'TaskController@index')->name('tugas.index');
    Route::get('/tugas/create/{id?}', 'TaskController@create')->name('tugas.create');
    Route::post('/tugas', 'TaskController@store')->name('tugas.store');
    Route::get('/tugas/{teacher_id}/{subject_id}', 'TaskController@edit')->name('tugas.edit');
    Route::put('/tugas/{teacher_id}/{subject_id}', 'TaskController@update')->name('tugas.update');
    Route::delete('/tugas/{teacher_id}/{subject_id}', 'TaskController@destroy')->name('tugas.destroy');

    Route::get('/jadwal/preview', 'ScheduleController@preview')->name('jadwal.preview');
    Route::get('/jadwal/cetak', 'ScheduleController@cetak')->name('jadwal.cetak');
    Route::resource('/jadwal', 'ScheduleController');

    Route::get('/generate', 'GenerateController@index')->name('generate.index');
    Route::get('/generate-jadwal', 'GenerateController@generate')->name('generate.jadwal');
    Route::post('/generate-jadwal', 'GenerateController@store')->name('generate.jadwal.store');

    Route::get('/ajax/tugas-guru/{id}', 'AjaxController@TaskTeacher');
    Route::get('/ajax/hari/{id}', 'AjaxController@day');
    Route::get('/ajax/kelas/{id}', 'AjaxController@grade');
    Route::get('/ajax/mata-pelajaran/{id}', 'AjaxController@subjectByClass');
    Route::get('/ajax/guru/{classLevelId}/{subjectId}/', 'AjaxController@teacher');

    Route::get('/home', 'MainController@home')->name('home');
});

resources/views/app/guru/create.blade.php
@extends('layouts.app')

@section('content')
<div class="card container">
    <div class="card-body">
        <h5 class="card-title">Tambah Guru</h5>
        @include('includes.pesan')
        <form action="{{ route('guru.store') }}" method="post">
            @csrf
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="">ID / Kode Guru</label>
                        <input type="text" name="id" class="form-control" value="{{ old('id') }}">
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="form-group">
                        <label for="">Nama Guru</label>
                        <input type="text" name="nama" class="form-control" value="{{ old('nama') }}">
                    </div>
                </div>
            </div>

            <button type="submit" class="btn btn-success mr-2">Simpan</button>
            <a href="{{ session('url_guru') }}">
                <button type="button" class="btn btn-secondary mr-2">Kembali</button>
            </a>
        </form>
    </div>
</div>
@endsection

resources/views/app/guru/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="card container">
    <div class="card-body">
        <h5 class="card-title">Edit Guru</h5>
        @include('includes.pesan')
        <form action="{{ route('guru.update', $teacher->id) }}" method="post">
            @csrf
            @method('PUT')
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="">ID / Kode Guru</label>
                        <input type="text" name="id" class="form-control" value="{{ old('id', $teacher->id) }}">
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="">Nama Guru</label>
                        <input type="text" name="nama" class="form-control" value="{{ old('nama', $teacher->nama) }}">
                    </div>
                </div>
            </div>

            <button type="submit" class="btn btn-success mr-2">Simpan</button>
            <a href="{{ session('url_guru') }}">
                <button type="button" class="btn btn-secondary mr-2">Kembali</button>
            </a>
        </form>
    </div>
</div>
@endsection

resources/views/app/guru/index.blade.php
@extends('layouts.app')

@section('content')
<div class="card container">
    <div class="card-body">
        <h5 class="card-title">Guru</h5>
        @include('includes.pesan')
        <form class="form-inline mb-3" action="{{ route('guru.index') }}">
            <input type="text" name="nama" class="form-control mb-2 mr-2" style="min-width:25%;" placeholder="Nama Guru" value="{{ request()->nama }}">
            <button type="submit" class="btn btn-primary mb-2 mr-1" type="button"><i class="fas fa-search"></i></button>
            <a href="{{ route('guru.create') }}" class="btn btn-success mb-2 mr-1"><i class="fas fa-plus"></i></a>
            <a href="{{ route('guru.index') }}" class="btn btn-info mb-2 mr-1"><i class="fas fa-sync-alt"></i></a>
            <a href="{{ route('home') }}" class="btn btn-secondary mb-2 mr-1"><i class="fas fa-arrow-left"></i></a>
        </form>

        <table id="datatable" class="table table-hover text-nowrap">
            <thead>
                <tr>
                    <th class="align-middle" rowspan="2">ID</th>
                    <th class="align-middle" rowspan="2">Nama Guru</th>
                    <th class="text-right pr-4">aksi</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($teachers as $teacher)
                <tr @if($teacher->id == session()->get('updated_id')) class="table-success" @endif>
                    <td>{{ $teacher->id }}.</td>
                    <td>{{ $teacher->nama }}</td>
                    <td class="text-right">
                        <a href="{{ route('guru.edit', $teacher->id) }}">
                            <i class="fas fa-edit text-info mr-2"></i>
                        </a>
                        <form method="POST" class="d-inline-block" action="{{ route('guru.destroy', $teacher->id) }}">
                            @csrf
                            @method('DELETE')
                            <a href="#" class="btn-delete">
                                <i class="fas fa-times text-danger mr-2"></i>
                            </a>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>

        <div class="d-flex justify-content-center">
            {{ $teachers->appends($_GET)->links() }}
        </div>
    </div>
</div>
@endsection