routes/web.php
<?php

Auth::routes();
Route::group(['middleware' => ['auth']], function () {
    Route::get('/simple', 'SimpleController@simpleGeneticAlgorithms');

    Route::get('/', 'MainController@home')->name('home');
    Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout')->name('logout');
    Route::get('/ubah-password', 'MainController@changePassword')->name('ubah.password');
    Route::put('/ubah-password', 'MainController@updatePassword')->name('update.password');

    Route::resource('/waktu', 'TimeController');
    Route::resource('/kelas', 'GradeController');
    Route::resource('/pelajaran', 'SubjectController');
    Route::resource('/guru', 'TeacherController');

    //Tugas
    Route::get('/tugas', 'TaskController@index')->name('tugas.index');
    Route::get('/tugas/create/{id?}', 'TaskController@create')->name('tugas.create');
    Route::post('/tugas', 'TaskController@store')->name('tugas.store');
    Route::get('/tugas/{teacher_id}/{subject_id}', 'TaskController@edit')->name('tugas.edit');
    Route::put('/tugas/{teacher_id}/{subject_id}', 'TaskController@update')->name('tugas.update');
    Route::delete('/tugas/{teacher_id}/{subject_id}', 'TaskController@destroy')->name('tugas.destroy');

    Route::get('/jadwal/preview', 'ScheduleController@preview')->name('jadwal.preview');
    Route::get('/jadwal/cetak', 'ScheduleController@cetak')->name('jadwal.cetak');
    Route::resource('/jadwal', 'ScheduleController');

    Route::get('/generate', 'GenerateController@index')->name('generate.index');
    Route::get('/generate-jadwal', 'GenerateController@generate')->name('generate.jadwal');
    Route::post('/generate-jadwal', 'GenerateController@store')->name('generate.jadwal.store');

    Route::get('/ajax/tugas-guru/{id}', 'AjaxController@TaskTeacher');
    Route::get('/ajax/hari/{id}', 'AjaxController@day');
    Route::get('/ajax/kelas/{id}', 'AjaxController@grade');
    Route::get('/ajax/mata-pelajaran/{id}', 'AjaxController@subjectByClass');
    Route::get('/ajax/guru/{classLevelId}/{subjectId}/', 'AjaxController@teacher');

    Route::get('/home', 'MainController@home')->name('home');
});

app/Models/Schedule.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Schedule extends Model
{
    //
    public function time()
    {
        return $this->belongsTo('App\Models\Time');
    }

    public function subject()
    {
        return $this->belongsTo('App\Models\Subject');
    }

    public function teacher()
    {
        return $this->belongsTo('App\Models\Teacher');
    }

    public function grade()
    {
        return $this->belongsTo('App\Models\Grade');
    }

    public static function fetch($request, $paginate = 10)
    {
        return $schedules = self::with('time', 'time.day', 'teacher', 'subject', 'grade')
            ->whereHas('time', function($query) use ($request) {
                $query->orderBy('jam_mulai');
                if ($request->jam_mulai) $query->where('jam_mulai', 'like', "%$request->jam_mulai%");
                if ($request->jam_selesai) $query->where('jam_selesai', 'like', "%$request->jam_selesai%");
                if ($request->day_id) $query->where('day_id', $request->day_id);
            })
            ->whereHas('grade', function($query) use ($request) {
                $query->orderBy('nama');
                if ($request->nama_kelas) $query->where('nama', 'like', "%$request->nama_kelas%");
                if ($request->tingkat_kelas) $query->where('class_level_id', "$request->tingkat_kelas");
            })
            ->where(function ($query) use ($request) {
                if ($request->subject) {
                    $query->whereHas('subject', function ($q) use ($request) {
                        $q->where('nama', 'like', "%$request->subject%");
                    });
                }

                if ($request->teacher) {
                    $query->whereHas('teacher', function($q) use ($request) {
                        if ($request->teacher) $q->where('nama', 'like', "%$request->teacher%");
                    });
                }

            })
            ->paginate($paginate);

    }

    public function getBentrokAttribute()
    {
        if ($this->subject_id == null) return null;
        $exist = self::with('grade')->where('time_id', $this->time_id)->where('teacher_id', $this->teacher_id)->whereNotIn('id', [$this->id])->get();
        return $exist;
        return null;
    }

    public function getOverloadAttribute()
    {
        if ($this->subject_id == null) return false;
        $day_id = Time::where('id', $this->time_id)->first()->day_id;
        $times = Time::where('day_id', $day_id)->get();
        $timeIds = $times->pluck('id');
        $schedules = self::whereIn('time_id', $timeIds)->where('grade_id', $this->grade_id)->where('subject_id', $this->subject_id)->get();
        $subject = Subject::find($this->subject_id);
        $jam = explode(' ', $subject->jam);
        $maxJam = max($jam);
        $totalJamPelajaran = count($schedules);
        if ($totalJamPelajaran > $maxJam) return $totalJamPelajaran - $maxJam;
        return false;
    }

    public static function byGradeId($gradeId)
    {
        return self::join('grades', 'schedules.grade_id', '=', 'grades.id')
            ->join('times', 'schedules.time_id', '=', 'times.id')
            ->with('subject')
            ->select('schedules.*', 'times.jam_mulai', 'times.jam_selesai', 'grades.nama as nama_kelas', 'grades.class_level_id')
            ->where('schedules.grade_id', $gradeId)
            ->get();
    }

    public static function byClassLevel()
    {
        $schedules = [];
        $classLevels = ClassLevel::all();
        foreach ($classLevels as $level) {
            $nama = $level->nama;
            $grades = Grade::where('class_level_id', $level->id)->get();
            foreach ($grades as $key => $grade) {
                $schedules[$nama][$grade->nama] = self::byGradeId($grade->id);
            }
        }
        return $schedules;
    }
}

resources/views/app/jadwal/cetak.blade.php
@extends('layouts.app')

@section('styles')
<style>
    p {
        margin-bottom: 0px;
    }

    hr {
        border-top: 3px solid black;
        border-style: double;
    }

    @media print {
        @page {
            margin: 20px;
        }

        body {
            margin: 0px 0px 0px 0px;
        }

        table {
            font-size: 12px !important;
        }

        .break {
            page-break-after: always;
        }
    }

</style>
@endsection

@section('scripts')
<script>
    function cetak() {
        var Window = window.open("", "", "width=4000,height=4000");
        var head = document.head.innerHTML;
        var printcontent = document.getElementById("print").innerHTML;
        Window.document.body.innerHTML = head + printcontent;
        setTimeout(() => {
            Window.focus();
            Window.print();
            Window.close();
        }, 1500);
    }

</script>
@endsection

@section('content')
<div class="card">
    <div class="card-body" style="font-size: 13px;">
        <h5 class="card-title">
            <button class="btn btn-primary" onclick="cetak()">
                Cetak Jadwal
            </button>
        </h5>

        @foreach ($schedulesByClass as $schedulesByGrade)
        <div id="print">
            <div class="row mb-2">
                <div class="col-md-2">
                    <div style="position: absolute; top: 0; right: -50px">
                        <img class="float-right" height="110" src="{{ asset('assets/img/lambang-osis.jpg') }}" alt="">
                    </div>
                </div>
                <div class="col-md-8 h5">
                    <div class="text-center">
                        <p>PEMERINTAH PROVINSI KALIMANTAN BARAT</p>
                        <p>DINAS PENDIDIKAN DAN KEBUDAYAAN</p>
                        <p class="font-weight-bold">SMA NEGERI 1 NANGA PINOH</p>
                        <p style="font-size: 14px;">Jalan Kota Baru km. 1 Nanga Pinoh,Kab.Melawi, Pos:79672</p>
                        <p></p>
                        <p class="font-weight-bold">Akreditasi: A</p>
                    </div>
                </div>
                <div class="col-md-2">
                    <div style="position: absolute; left:-50px">
                        <img height="110" src="{{ asset('assets/img/lambang-sekolah.jpg') }}" alt="">
                    </div>
                </div>
            </div>
            <hr>
            <div class="row mb-2">
                <div class="col-md-2"></div>
                <div class="col-md-8 text-center h6 font-weight-bold">
                    <p>JADWAL PELAJARAN SEMESTER GENAP</p>
                    <p>TAHUN PELAJARAN {{ date("Y") - 1 }} / {{ date("Y") }}</p>
                </div>
                <div class="col-md-2"></div>
            </div>
            <table class="table small table-bordered table-sm d-print-block mb-2">
                <thead class="text-center">
                    <th class="align-middle" style="width: 1%">Hari</th>
                    <th class="align-middle" style="width: 90px;">Waktu</th>
                    <th class="align-middle" style="width: 1%">Jam ke</th>
                    @foreach ($schedulesByGrade as $nama_kelas => $schedules)
                    <th class="align-middle">{{ $nama_kelas }}</th>
                    @endforeach
                </thead>
                @php
                $pointer = -1;
                @endphp
                @foreach($days as $indexDay => $day)
                @php
                $count = count($day->times) + 1;
                if ($day->nama == 'Senin') {
                $count += 1;
                }
                @endphp
                <tr>
                    <td rowspan="{{ $count }}" class="h4 align-middle text-center text-capitalize">
                        @for ($i = 0; $i < strlen($day->nama); $i++)
                            <div>{{ $day->nama[$i] }}</div>
                            @endfor
                    </td>
                </tr>
                @foreach ($day->times as $indexTime => $time)
                @if($day->nama == 'Senin' && $indexTime == 0)
                <tr class="text-center">
                    <td>07.00 - 07.45</td>
                    <td>{{ $indexTime + 1 }}</td>
                    <td colspan="{{ count($schedulesByGrade) }}">UPACARA</td>
                </tr>
                @endif

                <tr class="text-center">
                    <td>{{ $time['jam_mulai'] }} - {{ $time['jam_selesai'] }}</td>
                    @if($day->nama == 'Senin')
                    <td>{{ $indexTime + 2 }}</td>
                    @else
                    <td>{{ $indexTime + 1 }}</td>
                    @endif
                    @php
                    $pointer += 1;
                    @endphp
                    @foreach ($schedulesByGrade as $nama_kelas => $schedules)
                    <td>{{ $schedules[$pointer]->subject->nama ?? '' }}</td>
                    @endforeach
                </tr>
                @endforeach
                @endforeach
            </table>
            <div class="row mt-3 mb-5 break">
                <div class="col-md-6">
                    <div class="float-left" style="font-size: 13px; margin-left: 150px;">
                        <p>Mengetahui Pengawas Pembina,</p>
                        <div style="margin-bottom: 95px"></div>
                        <p><strong><u>H. NURCHOLIS, S.Pd</u></strong></p>
                        <p>Pembina</p>
                        <p>NIP. 19620615 198601 1 004</p>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="float-right" style="font-size: 13px; margin-right: 150px;">
                        <p>Nannga Pinoh, <span class="text-uppercase">{{ Carbon\Carbon::now()->addMonths(1)->formatLocalized('%d %B %Y') }}</span></p>
                        <p>PLT. Kepala Sekolah</p>
                        <div style="margin-bottom: 75px"></div>
                        <p><strong><u>ANTONIUS TUKIMIN,S.Pd</u></strong></p>
                        <p>PLT. Kepala Sekolah</p>
                        <p>Pembina</p>
                        <p>NIP.198010112005021003</p>
                    </div>
                </div>
            </div>
            @endforeach
        </div>
    </div>
</div>
@endsection

resources/views/app/jadwal/create.blade.php
@extends('layouts.app')

@section('content')
<div class="card container">
    <div class="card-body">
        <h5 class="card-title">Tambah Jadwal</h5>
        @include('includes.pesan')
        <form action="{{ route('jadwal.store') }}" method="post">
            @csrf
            <div class="row">
                <div class="col-md-3">
                    <div class="form-group">
                        <label for="">Hari</label>
                        <select name="day_id" id="day_id" class="form-control mb-2 mr-2">
                            @foreach ($days as $day)
                            <option @if(old('day_id') == $day->id) selected @endif
                                value="{{ $day->id }}">{{ $day->nama }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label for="">Jam</label>
                        <select name="time_id" id="time_id" class="form-control select2 mb-2 mr-2"></select>
                    </div>
                </div>
                <div class="col-md-3">
                    <label for="">Tingkat Kelas</label>
                    @component('components.forms.selectTingkatKelas', [
                        'class' => 'mb-2 mr-2',
                        'classLevels' => $classLevels,
                        'null' => true,
                        'value' => request()->tingkat_kelas
                    ])
                    @endcomponent
                </div>
                <div class="col-md-3">
                    <label for="">Nama Kelas</label>
                    <select name="grade_id" id="grade_id" class="form-control select2 mb-2 mr-2"></select>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="">Mata Pelajaran</label>
                        <select name="subject_id" class="form-control" id="subject_id"></select>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="">Guru</label>
                        <input type="text" name="nama_guru" id="nama_guru" class="form-control" value="{{ old('nama_guru') }}" readonly>
                        <input type="hidden" name="teacher_id" id="teacher_id" class="form-control" value="{{ request('teacher_id') }}">
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-success mr-2">Simpan</button>
            <a href="{{ session('url_jadwal') }}">
                <button type="button" class="btn btn-secondary mr-2">Kembali</button>
            </a>
        </form>
    </div>
</div>
@endsection

@section('scripts')
<script>
    //initial awal
    var day_id = $("#day_id").val()
    var time_id =  @json(old('time_id'));
    var tingkat_kelas = @json(old('tingkat_kelas'));
    var grade_id = @json(old('grade_id'));
    var subject_id = @json(old('subject_id'));
    $('#tingkat_kelas').val(tingkat_kelas)
    getJam(day_id)
    getKelas(tingkat_kelas)
    getMataPelajaran(tingkat_kelas)

    $("#day_id").change(function () {
        var day_id = $(this).val()
        getJam(day_id)
    })

    function getJam(day_id) {
        if (day_id) {
            $.get(`${URL}/ajax/hari/${day_id}`, function (data) {
                $("#time_id").select2().empty()
                $("#time_id").select2({data: data})
                $("#time_id").select2("val", time_id);
            })
        } else {
            $("#time_id").select2().empty();
        }
    }

    $("#tingkat_kelas").change(function () {
        var class_level_id = $(this).val()
        getKelas(class_level_id)
        getMataPelajaran(class_level_id)
    })

    function getKelas(tingkat_kelas) {
        if (tingkat_kelas) {
            $.get(`${URL}/ajax/kelas/${tingkat_kelas}`, function (data) {
                $("#grade_id").select2().empty()
                $("#grade_id").select2({data: data})
                $('#grade_id').val(grade_id).trigger('change.select2');
            })
        } else {
            $("#grade_id").select2().empty();
        }
    }

    function getMataPelajaran(tingkat_kelas) {
        if (tingkat_kelas) {
            $.get(`${URL}/ajax/mata-pelajaran/${tingkat_kelas}`, function (data) {
                $("#subject_id").select2().empty()
                $("#subject_id").select2({data: data})
                $("#subject_id").select2("val", subject_id)

                var class_level_id = $("#tingkat_kelas").val()
                var subject_id = $("#subject_id").select2('val')
                getGuru(subject_id, class_level_id)
            })
        } else {
            $("#subject_id").select2().empty();
            $("#nama_guru").val(null)
            $("#teacher_id").val(null)
        }
    }

    $("#subject_id").change(function () {
        var subject_id = $(this).val()
        var class_level_id = $("#tingkat_kelas").val()
        getGuru(subject_id, class_level_id)
    })

    function getGuru(subject_id, class_level_id) {
        if (subject_id && class_level_id) {
            $.get(`${URL}/ajax/guru/${subject_id}/${class_level_id}`, function (data) {
                $("#nama_guru").val(data.nama)
                $("#teacher_id").val(data.id)
            })
        } else {
            $("#nama_guru").val(null)
            $("#teacher_id").val(null)
        }
    }
</script>
@endsection

resources/views/app/jadwal/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="card container">
    <div class="card-body">
        <h5 class="card-title">Edit Jadwal</h5>
        @include('includes.pesan')
        @if(count($schedule->bentrok) > 0)
            <div class="alert alert-danger" role="alert">
                @foreach ($schedule->bentrok as $bentrok)
                    <li>Bentrok dengan kelas {{ $bentrok->grade->nama }}</li>
                @endforeach
            </div>
        @endif
        @if ($schedule->overload)
            <div class="alert alert-warning" role="alert">
                <li>Terdapat lebih dari {{ $schedule->overload }} jam pelajaran dalam satu hari</li>
            </div>
        @endif
        <form action="{{ route('jadwal.update', $schedule->id) }}" method="post">
            @csrf
            @method('PUT')
            <div class="row">
                <div class="col-md-3">
                    <div class="form-group">
                        <label for="">Hari</label>
                        <select name="day_id" id="day_id" class="form-control mb-2 mr-2" readonly>
                            @foreach ($days as $day)
                            <option @if(old('day_id', $schedule->time->day_id) == $day->id) selected @endif
                                value="{{ $day->id }}">{{ $day->nama }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label for="">Jam</label>
                        <input type="hidden" name="time_id" value="{{ old('time_id', $schedule->time_id) }}">
                        <select name="time_id" id="time_id" class="form-control select2 mb-2 mr-2" readonly></select>
                    </div>
                </div>
                <div class="col-md-3">
                    <label for="">Tingkat Kelas</label>
                    @component('components.forms.selectTingkatKelas', [
                        'class' => 'mb-2 mr-2',
                        'classLevels' => $classLevels,
                        'null' => true,
                        'value' => request()->tingkat_kelas
                    ])
                    @endcomponent
                </div>
                <div class="col-md-3">
                    <label for="">Nama Kelas</label>
                    <select name="grade_id" id="grade_id" class="form-control select2 mb-2 mr-2"></select>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="">Mata Pelajaran</label>
                        <select name="subject_id" class="form-control" id="subject_id"></select>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="">Guru</label>
                        <input type="text" name="nama_guru" id="nama_guru" class="form-control" value="{{ old('nama_guru') }}" readonly>
                        <input type="hidden" name="teacher_id" id="teacher_id" class="form-control" value="{{ request('teacher_id') }}">
                    </div>
                </div>
            </div>

            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="kosong" name="kosong" value="1">
                <label class="form-check-label" for="kosong">Kosongkan Jadwal</label>
            </div>

            <button type="submit" class="btn btn-success mr-2">Simpan</button>
            <a href="{{ session('url_jadwal') }}">
                <button type="button" class="btn btn-secondary mr-2">Kembali</button>
            </a>
        </form>
    </div>
</div>
@endsection

@section('scripts')
<script>
    //initial awal
    var day_id = $("#day_id").val()
    var time_id =  @json(old('time_id', $schedule->time_id));
    var tingkat_kelas = @json(old('tingkat_kelas', $schedule->grade->class_level_id));
    var grade_id = @json(old('grade_id', $schedule->grade_id));
    var subject_id = @json(old('subject_id', $schedule->subject_id));
    $('#tingkat_kelas').val(tingkat_kelas)
    getJam(day_id)
    getKelas(tingkat_kelas)
    getMataPelajaran(tingkat_kelas, subject_id)
    $("#time_id").select2({disabled: true});
    $("#day_id").change(function () {
        var day_id = $(this).val()
        getJam(day_id)
    })

    function getJam(day_id) {
        if (day_id) {
            $.get(`${URL}/ajax/hari/${day_id}`, function (data) {
                $("#time_id").select2().empty()
                $("#time_id").select2({data: data})
                $('#time_id').val(time_id).trigger('change');
            })
        } else {
            $("#time_id").select2().empty();
        }
    }

    $("#tingkat_kelas").change(function () {
        var class_level_id = $(this).val()
        getKelas(class_level_id)
        getMataPelajaran(class_level_id)
    })

    function getKelas(tingkat_kelas) {
        if (tingkat_kelas) {
            $.get(`${URL}/ajax/kelas/${tingkat_kelas}`, function (data) {
                $("#grade_id").select2().empty()
                $("#grade_id").select2({data: data})
                $('#grade_id').val(grade_id).trigger('change');
            })
        } else {
            $("#grade_id").select2().empty();
        }
    }

    function getMataPelajaran(tingkat_kelas) {
        let id = subject_id;
        if (tingkat_kelas) {
            $.get(`${URL}/ajax/mata-pelajaran/${tingkat_kelas}`, function (data) {
                $("#subject_id").select2().empty()
                $("#subject_id").select2({data: data})
                $("#subject_id").val(id).trigger('change');

                var class_level_id = $("#tingkat_kelas").val()
                var subject_id = $("#subject_id").select2('val')
                getGuru(subject_id, class_level_id)
            })
        } else {
            $("#subject_id").select2().empty();
            $("#nama_guru").val(null)
            $("#teacher_id").val(null)
        }
    }

    $("#subject_id").change(function () {
        var subject_id = $(this).val()
        var class_level_id = $("#tingkat_kelas").val()
        getGuru(subject_id, class_level_id)
    })

    function getGuru(subject_id, class_level_id) {
        if (subject_id && class_level_id) {
            $.get(`${URL}/ajax/guru/${subject_id}/${class_level_id}`, function (data) {
                $("#nama_guru").val(data.nama)
                $("#teacher_id").val(data.id)
            })
        } else {
            $("#nama_guru").val(null)
            $("#teacher_id").val(null)
        }
    }
</script>
@endsection

resources/views/app/jadwal/index.blade.php
@extends('layouts.app')

@section('content')
<div class="card">
    <div class="card-body">
        <h5 class="card-title">Mata Pelajaran</h5>
        @include('includes.pesan')
        <form class="form-inline mb-3" action="{{ route('jadwal.index') }}">
            @component('components.forms.selectTingkatKelas', [
                    'class' => 'mb-2 mr-2',
                    'classLevels' => $classLevels,
                    'null' => true,
                    'value' => request()->tingkat_kelas
                ])
            @endcomponent
            <input type="text" name="nama_kelas" class="form-control mb-2 mr-2" placeholder="Nama Kelas" value="{{ request()->nama_kelas }}">
            <select name="day_id" class="form-control mb-2 mr-2">
                <option value="">Semua</option>
                @foreach ($days as $day)
                <option @if(request()->day_id == $day->id) selected @endif
                    value="{{ $day->id }}">{{ $day->nama }}</option>
                @endforeach
            </select>
            <input type="text" name="jam_mulai" class="form-control mb-2 mr-2" placeholder="Jam mulai" value="{{ request()->jam_mulai }}">
            <input type="text" name="jam_akhir" class="form-control mb-2 mr-2" placeholder="Jam akhir" value="{{ request()->jam_akhir }}">
            <input type="text" name="subject" class="form-control mb-2 mr-2" placeholder="Mata Pelajaran" value="{{ request()->subject }}">
            <input type="text" name="teacher" class="form-control mb-2 mr-2" placeholder="Guru" value="{{ request()->teacher }}">
            <button type="submit" class="btn btn-primary mb-2 mr-1" type="button"><i class="fas fa-search"></i></button>
            <a href="{{ route('jadwal.create') }}" class="btn btn-success mb-2 mr-1"><i class="fas fa-plus"></i></a>
            <a href="{{ route('jadwal.index') }}" class="btn btn-info mb-2 mr-1"><i class="fas fa-sync-alt"></i></a>
            <a href="{{ route('home') }}" class="btn btn-secondary mb-2 mr-1"><i class="fas fa-arrow-left"></i></a>
        </form>

        <table class="table small table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Kelas</th>
                    <th>Hari</th>
                    <th>Jam</th>
                    <th>Mata Pelajaran</th>
                    <th>Guru</th>
                    <th class="text-right pr-4">Aksi</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($schedules as $schedule)
                <tr
                    @if($schedule->id == session()->get('updated_id')) class="table-success" @endif
                    @if(count($schedule->bentrok) > 0) class="table-danger" @endif
                    @if($schedule->overload > 0) class="table-warning" @endif
                    >
                    <td>{{ ($schedules->currentpage() - 1) * $schedules->perPage() + $loop->iteration }}.</td>
                    <td>{{ $schedule->grade->nama }}</td>
                    <td>{{ $schedule->time->day->nama }}</td>
                    <td>{{ $schedule->time->jam_mulai }} - {{ $schedule->time->jam_selesai }}</td>
                    <td>{{ $schedule->subject->nama ?? ' - ' }}</td>
                    <td>{{ $schedule->teacher->nama ?? ' - ' }}</td>
                    <td class="text-right">
                        <a href="{{ route('jadwal.edit', $schedule->id) }}">
                            <i class="fas fa-edit text-info mr-2"></i>
                        </a>
                    </td>
                </tr>
                @endforeach
            </tbody>
            <tfoot>
            </tfoot>
        </table>

        <div class="d-flex justify-content-center">
            {{ $schedules->appends($_GET)->links() }}
        </div>
    </div>
</div>
@endsection

resources/views/app/jadwal/preview2.blade.php
@extends('layouts.app')

@section('content')
<div class="card">
    <div class="card-body">
        <h5 class="card-title"></h5>
        @foreach ($schedulesByClass as $nama_kelas => $schedules)
        <table class="table small table-bordered">
            <thead>
                <tr>
                    @php $count = count($schedules) + 3 @endphp
                    <th class="text-center" colspan="{{ $count }}">Kelas {{ $nama_kelas }}</th>
                </tr>
            </thead>
            <tr>
                <th>Hari</th>
                <th>Jam ke</th>
                <th>Waktu</th>
                @foreach ($schedules as $index => $schedule)
                    <th>{{ $index }}</th>
                @endforeach
            </tr>

            @php $before = null @endphp
            @foreach ($times as $index => $time)
                @php
                    if ($time->day_id != $before) $jam_ke = 1;
                    $before = $time->day_id;
                @endphp
                <tr>
                    @if ($jam_ke == 1)
                        <td>{{ $time->hari }}</td>
                    @else
                        <td></td>
                    @endif
                    <td>{{ $jam_ke++ }}</td>
                    <td>{{ $time->jam_mulai }} - {{ $time->jam_selesai }}</td>
                    @foreach ($schedules as $schedule)
                        @if (isset($schedule[$index]->subject->nama))
                            <td
                            @if(count($schedule[$index]->bentrok) > 0) class="table-danger" @endif
                            @if($schedule[$index]->overload > 0) class="table-warning" @endif
                            >{{ $schedule[$index]->subject->nama }}</td>
                        @else
                            <td> - </td>
                        @endif
                    @endforeach
                </tr>
            @endforeach
        </table>
        @endforeach
    </div>
</div>
@endsection